### ISSUE TITLE
oldView.$el doesn't exist

### ISSUE THREAD

**Issue by Nedudi** [marcinkrysiak1979/marionette.showAnimated#3]
Hi! Great plugin, love it!
The only one issue I have is:
if I don't have old view it cause a error because oldView.$el doesn't exist
in this case, I propose to call show instead of showAnimated inside plugin.

This is common case when you show your view first time inside region

**Comment by marcin-krysiak** [comment]
Hi Nedudi

Thanks for your feedback.

I will fix the issue tomorrow

Many thanks and let me know any further thoughts.
Marcin

**Comment by marcin-krysiak** [comment]
Hi Nedudi

I just fixed the issue and it should be fine now

Many thanks
Marcin
